name: "bicep-build-and-apply"
  
inputs:
  environmentName:
    description: "The name of the environment e.g. dev, prd"
    required: true
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string
  
runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Az CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build Bicep
      shell: bash
      run: |
        az bicep build --file bicep/platform.bicep --stdout
        az bicep build --file bicep/workload.bicep --stdout

    - name: Validate Bicep
      shell: pwsh
      run: |
        $config = (Get-Content params/platform.${{ inputs.environmentName }}.json | ConvertFrom-Json)

        az deployment sub validate `
          --name "portal-servers-integration-platform-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          --location $config.parameters.parLocation.value `
          --template-file bicep/platform.bicep `
          --parameters @params/platform.$($config.parameters.parEnvironment.value).json

        if ((az group exists --name "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)") -eq $true) {
          az deployment group validate `
            --name "portal-servers-integration-workload-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
            --resource-group "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)" `
            --template-file bicep/workload.bicep `
            --parameters @params/workload.$($config.parameters.parEnvironment.value).json `
              parServersIntegrationApiAppId=00000000-0000-0000-0000-000000000000
        }

    - name: WhatIf Bicep
      shell: pwsh
      run: |
        $config = (Get-Content params/platform.${{ inputs.environmentName }}.json | ConvertFrom-Json)

        az deployment sub what-if `
          --name "portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          --location $config.parameters.parLocation.value `
          --template-file bicep/platform.bicep `
          --parameters @params/platform.$($config.parameters.parEnvironment.value).json

        if ((az group exists --name "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)") -eq $true) {
          az deployment group what-if `
            --name "portal-servers-integration-workload-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
            --resource-group "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)" `
            --template-file bicep/workload.bicep `
            --parameters @params/workload.$($config.parameters.parEnvironment.value).json `
              parServersIntegrationApiAppId=00000000-0000-0000-0000-000000000000
        }

    - name: Deploy Platform Bicep
      shell: pwsh
      run: |
        $config = (Get-Content params/platform.${{ inputs.environmentName }}.json | ConvertFrom-Json)

        $deletedKeyVaults = az keyvault list-deleted --query '[].properties.vaultId' | ConvertFrom-Json
        $isDeleted = $deletedKeyVaults | where {$_ -match "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)"}

        $keyVaultCreateMode = "default"
        if ($isDeleted -ne $null) {
          # To allow the development environment to be torn-down and re-created, the Key Vault Create Mode must be set to 'recover'.
          $keyVaultCreateMode = "recover"
        }

        az deployment sub create `
          --name "portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          --location $config.parameters.parLocation.value `
          --template-file bicep/platform.bicep `
          --parameters @params/platform.$($config.parameters.parEnvironment.value).json `
          parKeyVaultCreateMode=$keyVaultCreateMode

    - name: Platform AAD Scripts
      shell: pwsh
      run: |
        $config = (Get-Content params/platform.${{ inputs.environmentName }}.json | ConvertFrom-Json)

        $keyVaultName = az deployment sub show --name portal-servers-integration-platform-${{ inputs.environmentName }} --subscription ${{ inputs.AZURE_SUBSCRIPTION_ID }} --query properties.outputs.keyVaultName.value

        . scripts/CreateAppRegistration.ps1 -applicationName "portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          -appRoles "portal-servers-integration-approles.json"
        
        . scripts/CreateAppRegistrationCredential.ps1 -keyVaultName $keyVaultName `
          -applicationName "portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          -secretPrefix "portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          -secretDisplayName "portalserversintegration"

    - name: Deploy Workload Bicep
      shell: pwsh
      run: |
        $config = (Get-Content params/platform.${{ inputs.environmentName }}.json | ConvertFrom-Json)

        $serversIntegrationApiName = "portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)"
        $serversIntegrationApiAppId = (az ad app list --filter "displayName eq '$serversIntegrationApiName'" --query '[].appId') | ConvertFrom-Json

        az deployment group create --resource-group "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)" `
          --name "portal-servers-integration-workload-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" `
          --template-file bicep/workload.bicep `
          --parameters @params/workload.$($config.parameters.parEnvironment.value).json `
          parServersIntegrationApiAppId=$serversIntegrationApiAppId 

    - name: Workload AAD Scripts
      shell: pwsh
      run: |
        $config = (Get-Content params/workload.${{ inputs.environmentName }}.json | ConvertFrom-Json)

        $deploymentOutput = (az deployment group show --name "portal-servers-integration-workload-$($config.parameters.parEnvironment.value)-$($config.parameters.parInstance.value)" --resource-group "rg-portal-servers-integration-$($config.parameters.parEnvironment.value)-$($config.parameters.parLocation.value)-$($config.parameters.parInstance.value)") | ConvertFrom-Json
        
        $repositoryApiName = $config.parameters.parRepositoryApi.value.ApplicationName
        $repositoryApiId = (az ad app list --filter "displayName eq '$repositoryApiName'" --query '[].appId') | ConvertFrom-Json
        $resourceId = (az ad sp list --filter "appId eq '$repositoryApiId'" --query '[0].id') | ConvertFrom-Json
        $repositoryApiSpn = (az rest -m GET -u https://graph.microsoft.com/v1.0/servicePrincipals/$resourceId) | ConvertFrom-Json
        $appRoleId = ($repositoryApiSpn.appRoles | Where-Object { $_.displayName -eq "ServiceAccount" }).id

        $principalId = $deploymentOutput.properties.outputs.principalId.value
        . "scripts/GrantPrincipalAppRole.ps1" -principalId $principalId -resourceId $resourceId -appRoleId $appRoleId

