name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions: {}

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: frasermolyneux/actions/copilot-setup@copilot-setup/v2
        with:
          checkout-repo: 'false'
          setup-dotnet: 'true'
          dotnet-version: '10.0.301'
